name: tsumihebi
version: 0.0.1
category: Language
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/tsumihebi

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - async
  - base >= 4.9 && < 4.10
  - bytestring
  - cpphs
  - deepseq
  - extra
  - filepath
  - temporary
  - utf8-string

library:
  source-dirs: src
